export const Foods: any[] = [
  {
    id:'0',
    name: 'Lemon pistachio biscotti',
    price: 50,
    cookTime: '20-30',
    favorite: true,
    origins: ['Italian cuisine'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/1.png?alt=media&token=05815658-6fdb-4587-86ec-fae5113c03aa',
    tags: ['Biscotti', 'Low blood sugar'],
  },
  {
    id:'1',
    name: 'Dark chocolate and almond biscotti',
    price: 50,
    cookTime: '20-30',
    favorite: false,
    origins: ['Italian cuisine'],
    stars: 4.3,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/2.png?alt=media&token=28b0c47d-fe87-4c80-9d7a-4a40d5b38c73',
    tags: ['Biscotti', 'Low blood sugar'],
  },
  {
    id:'2',
    name: 'Orange cranberry biscotti',
    price: 55,
    cookTime: '20-30',
    favorite: true,
    origins: ['Italian cuisine'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/3.png?alt=media&token=85cf5054-5891-4eeb-bf0e-b78e71514fde',
    tags: ['Biscotti', 'Low blood sugar'],
  },
  {
    id:'3',
    name: 'Dried-fruit Biscotti',
    price: 60,
    cookTime: '20-30',
    favorite: false,
    origins: ['Italian cuisine'],
    stars: 4.6,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/4.png?alt=media&token=ef68ee4c-9014-4cf0-8e13-da6f972a72f7',
    tags: ['Biscotti', 'Low blood sugar'],
  },
  {
    id:'4',
    name: 'Whole Wheat Biscotti',
    price: 40,
    cookTime: '15-30',
    favorite: true,
    origins: ['Italian cuisine'],
    stars: 4.6,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/5.png?alt=media&token=e1928882-d30a-448a-aace-6900ba53a3cd',
    tags: ['Biscotti', 'Low blood sugar'],
  },
  {
    id:'5',
    name: 'Dark chocolate pistachio biscotti',
    price: 50,
    cookTime: '30-40',
    favorite: false,
    origins: ['Italian cuisine'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/6.png?alt=media&token=041ad1e5-5bfa-4a4e-abba-2a6f7a5efbd0',
    tags: ['Biscotti', 'Low blood sugar'],
  },
  {
    id:'6',
    name: 'Dried-rose hazelnut biscotti',
    price: 48,
    cookTime: '20-30',
    favorite: false,
    origins: ['Italian cuisine'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/7.png?alt=media&token=53c9c3db-442b-4a3e-b5ff-715ebb5748e6',
    tags: ['Biscotti', 'Low blood sugar'],
  },
  {
    id:'7',
    name: 'Oatmeal Raisin Cookies',
    price: 100,
    cookTime: '10-20',
    favorite: true,
    origins: ['Cookies'],
    stars: 4,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/8.png?alt=media&token=698aa8d8-5cff-4628-bac4-ae436ca30155',
    tags: ['Workout'],
  },
  {
    id:'8',
    name: 'Matcha Cookies',
    price: 120,
    cookTime: '10-20',
    favorite: true,
    origins: ['Cookies'],
    stars: 4.7,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/9.png?alt=media&token=aa4c779a-4c58-4be2-aba6-19a42530cec7',
    tags: ['Workout'],
  },
  {
    id:'9',
    name: 'Oatmeal Raisin Cookies',
    price: 65,
    cookTime: '10-20',
    favorite: false,
    origins: ['Cookies'],
    stars: 4.7,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/10.png?alt=media&token=587345d8-de38-463f-a48b-c0324db176da',
    tags: ['Workout'],
  },
  {
    id:'10',
    name: 'Vegan Lemon Cookies',
    price: 72,
    cookTime: '20-30',
    favorite: true,
    origins: ['Cookies'],
    stars: 4,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/11.png?alt=media&token=e7404b37-32bf-40a4-a40f-c46308ac1e8e',
    tags: ['Workout'],
  },
  {
    id:'11',
    name: 'Oatmeal Cookies',
    price: 60,
    cookTime: '10-20',
    favorite: false,
    origins: ['Cookies'],
    stars: 4,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/12.png?alt=media&token=663eb4da-ace7-43c6-815e-8820dd929ff6',
    tags: ['Workout'],
  },
  {
    id:'12',
    name: 'Pecan Nut Butter',
    price: 90,
    cookTime: '0-10',
    favorite: true,
    origins: ['Butter'],
    stars: 4.9,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/13.png?alt=media&token=6a6d433a-70ce-4fbe-bb17-0f914be706d4',
    tags: ['High in fiber'],
  },
  {
    id:'13',
    name: 'Cinnamon raisin almond butter',
    price: 80,
    cookTime: '10-20',
    favorite: false,
    origins: ['Butter'],
    stars: 4.4,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/14.png?alt=media&token=ae11d357-3c79-47f1-84b8-ffda1950079b',
    tags: ['High in fiber'],
  },
  {
    id:'14',
    name: 'Coconut butter',
    price: 70,
    cookTime: '0-10',
    favorite: true,
    origins: ['Butter'],
    stars: 4.2,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/15.png?alt=media&token=544a48a5-7c17-4e56-86e7-329851dedf98',
    tags: ['High in fiber'],
  },
  {
    id:'15',
    name: 'Chocolate hazelnut butter',
    price: 85,
    cookTime: '20-30',
    favorite: true,
    origins: ['Butter'],
    stars: 4.9,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/16.png?alt=media&token=c476b26d-3387-4d36-85c1-06bc4dd2a272',
    tags: ['High in fiber'],
  },
  {
    id:'16',
    name: 'Dried strawberry',
    price: 125,
    cookTime: '0-10',
    favorite: true,
    origins: ['vitamins', 'minerals'],
    stars: 5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/17.png?alt=media&token=adb1dbb8-145a-4deb-a992-1da8a7179360',
    tags: ['High in fiber'],
  },
  {
    id:'17',
    name: 'Dried banana',
    price: 60,
    cookTime: '0-10',
    favorite: false,
    origins: ['vitamins', 'minerals'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/18.png?alt=media&token=1725077d-e7a0-44d2-a716-11ba8111817d',
    tags: ['High in fiber'],
  },
  {
    id:'18',
    name: 'Dried banana',
    price: 45,
    cookTime: '0-10',
    favorite: false,
    origins: ['vitamins', 'minerals'],
    stars: 4.7,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/19.png?alt=media&token=38e2abd7-541f-4884-bc58-623037e81147',
    tags: ['High in fiber'],
  },
  {
    id:'19',
    name: 'Dried apricot',
    price: 110,
    cookTime: '0-10',
    favorite: true,
    origins: ['vitamins', 'minerals'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/20.png?alt=media&token=a2f89b0f-b9e4-4937-b202-2400d6fcd261',
    tags: ['High in fiber'],
  },
  {
    id:'20',
    name: 'Dried cranberries',
    price: 150,
    cookTime: '0-10',
    favorite: false,
    origins: ['vitamins', 'minerals'],
    stars: 4.4,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/21.png?alt=media&token=7ea7fb82-24a2-4457-9c66-ea60e3db54be',
    tags: ['High in fiber'],
  },
  {
    id:'21',
    name: 'Raisins',
    price: 100,
    cookTime: '0-10',
    favorite: false,
    origins: ['vitamins', 'minerals'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/22.png?alt=media&token=f6a40456-aa86-4663-83ce-0c7699d25af7',
    tags: ['High in fiber'],
  },
  {
    id:'22',
    name: 'Baked sweet potatoes',
    price: 55,
    cookTime: '0-10',
    favorite: true,
    origins: ['vitamins A', 'vitamins C'],
    stars: 4.8,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/23.png?alt=media&token=01769584-61eb-4f97-8e17-19796727c3a7',
    tags: ['High in fiber'],
  },
  {
    id:'23',
    name: 'Dried carrots',
    price: 45,
    cookTime: '0-10',
    favorite: false,
    origins: ['vitamins A', 'vitamins C'],
    stars: 4.2,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/24.png?alt=media&token=5b2c39f5-16d0-493c-ab70-01bc66cc7f6c',
    tags: ['High in fiber'],
  },
  {
    id:'24',
    name: 'Dried Shiitake mushrooms',
    price: 100,
    cookTime: '0-10',
    favorite: true,
    origins: ['robust umami flavor'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/25.png?alt=media&token=f4447a9d-0f69-4165-a972-fa427455c598',
    tags: ['High in fiber'],
  },
  {
    id:'25',
    name: 'Dried beets',
    price: 65,
    cookTime: '0-10',
    favorite: false,
    origins: ['sweet and earthy flavor'],
    stars: 4.7,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/26.png?alt=media&token=6da650ec-a9cc-4f09-84ee-724ca07e8822',
    tags: ['High in fiber'],
  },
  {
    id:'26',
    name: 'Dried chickpeas',
    price: 110,
    cookTime: '0-10',
    favorite: false,
    origins: ['rich in protein'],
    stars: 4.6,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/27.png?alt=media&token=39d8bc65-4d75-4b6e-a902-1b295eaf986f',
    tags: ['High in fiber'],
  },
  {
    id:'27',
    name: 'Chocolate Granola',
    price: 45,
    cookTime: '10-20',
    favorite: true,
    origins: ['flavor of chocolate'],
    stars: 4.8,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/28.png?alt=media&token=6ac81a5c-7915-41a6-b208-d51e11df7c79',
    tags: ['Fast meals', 'Low blood sugar', 'Workout'],
  },
  {
    id:'28',
    name: 'Premium mixed nuts',
    price: 139,
    cookTime: '10-20',
    favorite: false,
    origins: ['satisfying crunch'],
    stars: 4.6,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/29.png?alt=media&token=b396429d-1244-414b-8771-21994ac86554',
    tags: ['Fast meals', 'Low blood sugar', 'Workout'],
  },
  {
    id:'29',
    name: 'Pineapple-flavoured granola',
    price: 48,
    cookTime: '10-20',
    favorite: true,
    origins: ['flavor of pineapple'],
    stars: 4.1,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/30.png?alt=media&token=a6b80188-469f-4355-b2e3-2c98f07b1a9f',
    tags: ['Fast meals', 'Low blood sugar'],
  },
  {
    id:'30',
    name: 'Premium Australian macadamia',
    price: 80,
    cookTime: '0-10',
    favorite: false,
    origins: ['buttery flavor'],
    stars: 4.9,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/31.png?alt=media&token=5f57ddec-f063-4fdc-b82e-b195ba00f919',
    tags: ['Fast meals', 'Low blood sugar', 'Workout'],
  },
  {
    id:'31',
    name: 'Matcha-flavored granola',
    price: 50,
    cookTime: '0-10',
    favorite: false,
    origins: ['nutritious'],
    stars: 4.6,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/32.png?alt=media&token=5f6ff7bd-c4fb-46e0-82b4-9939b624f5d0',
    tags: ['Fast meals', 'Low blood sugar'],
  },
  {
    id:'32',
    name: 'Premium roasted green pumpkin seeds',
    price: 40,
    cookTime: '0-10',
    favorite: false,
    origins: ['healthy fats'],
    stars: 4.3,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/33.png?alt=media&token=ba247f6d-7147-4757-9352-93546d664ffe',
    tags: ['Fast meals'],
  },
  {
    id:'33',
    name: 'Matcha-flavored granola',
    price: 75,
    cookTime: '0-10',
    favorite: false,
    origins: ['omega-3'],
    stars: 4.4,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/34.png?alt=media&token=70cba085-c2bd-4cf7-acd4-6af2ee9e2554',
    tags: ['Fast meals', 'Low blood sugar', 'Workout'],
  },
  {
    id:'34',
    name: 'Roasted raw cashews',
    price: 50,
    cookTime: '0-10',
    favorite: false,
    origins: ['creamy texture'],
    stars: 4.3,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/35.png?alt=media&token=989b6ff6-2818-4897-bc95-cba0451f4cdd',
    tags: ['Fast meals'],
  },
  {
    id:'35',
    name: 'Premium Traditional Flavor Granola Without Sugar',
    price: 125,
    cookTime: '0-10',
    favorite: false,
    origins: ['classic granola'],
    stars: 5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/37.png?alt=media&token=c14e3ce1-02b1-4c7f-a48d-f08ddab35167',
    tags: ['Fast meals', 'Low blood sugar', 'Workout'],
  },
  {
    id:'36',
    name: 'Almond Milk',
    price: 30,
    cookTime: '20-30',
    favorite: true,
    origins: ['low in calories and fat'],
    stars: 4.8,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/36.png?alt=media&token=673b3a97-71c4-4a64-9cbd-3cc4585e5c3d',
    tags: ['Vegan', 'Low blood sugar'],
  },
  {
    id:'37',
    name: 'Oat Milk',
    price: 30,
    cookTime: '20-30',
    favorite: false,
    origins: ['naturally sweet flavor'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/39.png?alt=media&token=654b456f-84ce-4686-81e3-1e51653e0fef',
    tags: ['Vegan','Low blood sugar'],
  },
  {
    id:'38',
    name: 'Coconut milk',
    price: 25,
    cookTime: '20-30',
    favorite: true,
    origins: ['tropical flavor'],
    stars: 4.8,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/40.png?alt=media&token=e15d0bd0-7afc-4cbd-8eab-e227c01ed3bb',
    tags: ['Vegan', 'Low blood sugar'],
  },
  {
    id:'39',
    name: 'Cashew milk',
    price: 30,
    cookTime: '20-30',
    favorite: false,
    origins: ['vitamin E'],
    stars: 4.7,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/41.png?alt=media&token=3ef9a631-52b7-4dbe-9c84-354d1dfbf781',
    tags: ['Vegan', 'Low blood sugar'],
  },
  {
    id:'40',
    name: 'Soy Milk',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['rich in protein'],
    stars: 4.9,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/42.png?alt=media&token=cc97b278-6c17-451c-8bd4-1f8041e4666d',
    tags: ['Vegan', 'Low blood sugar'],
  },
  {
    id:'41',
    name: 'Organic rye bread',
    price: 45,
    cookTime: '20-30',
    favorite: false,
    origins: ['sweetness'],
    stars: 4.4,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/43.png?alt=media&token=e3de2a87-ae25-4acf-a3b1-fcd28455ab0c',
    tags: ['Fast meals', 'Low blood sugar'],
  },
  {
    id:'42',
    name: 'Organic wholemeal bread',
    price: 40,
    cookTime: '20-30',
    favorite: true,
    origins: ['nutrients and fiber'],
    stars: 4.6,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/44.png?alt=media&token=f10d5ce0-dd3a-4e2a-b19e-e19065dffe0a',
    tags: ['Fast meals', 'Low blood sugar'],
  },
  {
    id:'43',
    name: 'Roasted pumpkin seed bread',
    price: 49,
    cookTime: '20-30',
    favorite: false,
    origins: ['crunch of autumn'],
    stars: 4.1,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/45.png?alt=media&token=1c0d4206-0f5b-4852-bb8b-e75ea687cdc0',
    tags: ['Fast meals', 'Low blood sugar', 'Vegan'],
  },
  {
    id:'44',
    name: 'Roasted raisin bread',
    price: 37,
    cookTime: '20-30',
    favorite: false,
    origins: ['juicy raisins'],
    stars: 4.8,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/46.png?alt=media&token=4b70c086-6f8f-45eb-8b66-460231fc265f',
    tags: ['Fast meals', 'Low blood sugar', 'Vegan'],
  },
  {
    id:'45',
    name: 'Cookie dough cashew butter',
    price: 50,
    cookTime: '20-30',
    favorite: false,
    origins: ['creamy richness'],
    stars: 4.8,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/47.png?alt=media&token=c71eefc2-4ded-4623-8883-ef3e2c0769d9',
    tags: ['High in fiber'],
  },
  {
    id:'46',
    name: 'Strawberry unsalted butter',
    price: 55,
    cookTime: '20-30',
    favorite: false,
    origins: ['ripe strawberries'],
    stars: 4.5,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/48.png?alt=media&token=eee69393-0373-4212-be11-d56a6faafb90',
    tags: ['High in fiber'],
  },
  {
    id:'47',
    name: 'Granola energy bar',
    price: 50,
    cookTime: '10-20',
    favorite: true,
    origins: ['energy-sustaining ingredients'],
    stars: 4.9,
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/foodapplication-86a93.appspot.com/o/49.png?alt=media&token=3054e1a5-145b-417a-b543-afcb1beeab8e',
    tags: ['Fast meals', 'Low blood sugar','Workout'],
  },

]
export const Category:any[] = [
  { name: 'All', count: 48 },
  { name: 'Low blood sugar', count: 24 },
  { name: 'Vegan', count: 7 },
  { name: 'Workout', count: 11 },
  { name: 'High in fiber', count: 15 },
  { name: 'Fast meals', count: 14 },
]

export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];